/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nighttorch;

import java.net.Socket;
import java.io.DataOutputStream;
import java.net.ServerSocket;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;


public class App {

	/*static peer[] jumpstart_network(int ip_final){
		final byte[] ip;
		try {
			ip = InetAddress.getLocalHost().getAddress();
		}catch (Exception e){
			return null;
		}

		for (int ending = 1; ending <= 254; ending++){
			final int ending_final = ending;
			new Thread(new Runnable() {
				public void run() {
					try {
						ip[3] = (byte)ending_final;
						InetAddress address = InetAddress.getByAddress(ip);
						String output = address.toString().substring(1);
						if (address.isReachable(5000)) {
							System.out.println(output + " is on the network");
						} else {
							System.out.println("Not Reachable: "+output);
						}
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
			}).start();
		}
		
	}*/

    public static void main(String[] args) throws Exception{
		Peer peer = new Peer();
		peer.ip = "127.0.0.1";
		peer.port = 9000;
		peer.active = true;
		peer.protocol_version = 0;

		Client test_client = new Client(peer);

		test_client.send_echo();
    }
}
